name: ccChat
version: '${project.version}'
main: cc.cactu.minecraft.ccchat.CcChat
api-version: "1.21"
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.1.0
commands:
  m:
    description: Wyślij prywatną wiadomość do gracza
    usage: /m <nick> <wiadomość>
  r:
    description: Szybka odpowiedź na ostatnią wiadomość prywatną
    usage: /r <wiadomość>