main: io.cactu.mc.chat.Plugin
name: ccChat
version: 0.7

depend: [ KotlinRuntime ]

commands:
  m:
    description: Wyślij prywatną wiadomosć
    usage: /<command> <gracz> <...treść>
  "?":
    description: Pomoc
  help:
    description: Pomoc
  pomoc:
    description: Pomoc